### ISSUE TITLE
🟦 Bridging the feature gap for business surveys, including agriculture surveys

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Bowie#26]
# Business case
🇬🇧
To ensure that the functional coverage of Pogues/Eno/Lunatic is the one expected by the SSP

🇫🇷 
Faire en sorte que la couverture fonctionnelle des outils (en particulier Lunatic) permette de collecte les enquêtes entreprises et du SSP. 

# Stack

## Pogues
- [ ] access to Pogues

## Eno
- [ ] https://github.com/InseeFr/Lunatic/issues/237

## Lunatic
- [x] improve tables
- [x] pagination sequence and controls (https://github.com/InseeFr/Lunatic/issues/360)
- [x] pre-fill collected data (exp : Conj) : https://github.com/InseeFr/Lunatic/issues/361
- [x] controls : personalization of "error message"

## Stromae
- [x] First page of the questionnaire with "business" and/or "SSP" context, in addition to the context "household"  : https://github.com/InseeFr/Stromae/issues/208

## Transverses 
- [x] Tableaux dynamiques https://github.com/InseeFr/Bowie/issues/62

# Progress

# Release date
