### ISSUE TITLE
User requests - features that are not part of an epic, but on which we may work

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Bowie#40]
User requests
----------------------------------------------------------------------------------------------------

- [ ] Boucler sur une question ?
- [ ] Permettre que le min et le max de la date soient des variables calculées ou collectées (créer issue)
- [ ] Afficher une barre d'avancement 
- [ ] Espace qui disparait des libellés quand il y a une info bulle dans Pogues.
- [ ] Dimension zone InputNumber (mui ?)
- [x] Séparateurs de milliers (https://github.com/InseeFr/Lunatic/issues/133)
- [ ] QCM - QCU : utiliser le libellé et non le code (https://github.com/InseeFr/Lunatic/issues/236)
- [x] Bugs de navigation (Lunatic) - à surveiller avec Lunatic V2

**Comment by AnneHuSKa** [comment]
Créer des issues dans les autres repo
