### ISSUE TITLE
Lunatic : consolidation of loops

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Bowie#41]
# Business case
🇬🇧
Several improvements or bug fixes

🇫🇷
Reprendre les issues Lunatic et pointer le non bloquant non pris en compte à l'automne 2022

# Stack
Correct several bugs

## DDI
none

## Pogues
none

## Eno
maybe ?

## Lunatic
- [ ]  https://github.com/InseeFr/Lunatic/issues/230 Bug : rosterForLoop, loop built on it // ko when pagination = sequence
- [ ] https://github.com/InseeFr/Lunatic/issues/233 Bug - Validation Page is not reacheable when the last page of questionnaire is inside a Loop
- [ ] https://github.com/InseeFr/Eno/issues/1037 : If a loop contains the last sequence, the looped on elements are not display
- [ ] https://github.com/InseeFr/Lunatic/issues/212 : Bug - Table (with fixed size) not working inside a Loop Component 

# Progress
 

# Release date
March 2023

**Comment by AnneHuSKa** [comment]
Juste https://github.com/InseeFr/Eno/issues/1037, plus une epic

**Comment by AnneHuSKa** [comment]
Juste https://github.com/InseeFr/Eno/issues/1037, plus une epic
