### ISSUE TITLE
:blue_square: Business questionnaire needs (powered by Estanp)

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Bowie#70]
# Business case
This _epic_ list various needs expressed by the Insee Estanp project. These needs are enhancement for:
- the suggester component
- the dynamic table component

## Stakeholders

- the Estanp project

## Linked Epics
- [ ] https://github.com/InseeFr/Concevoir-Workplace/issues/19
- [ ] https://github.com/InseeFr/Bowie/issues/76
- [ ] https://github.com/InseeFr/Concevoir-Workplace/issues/31
- [ ] https://github.com/InseeFr/Bowie/issues/78
- [ ] https://github.com/InseeFr/Bowie/issues/80

### Lunatic
__Suggester__
- [x] https://github.com/InseeFr/Lunatic/issues/604
- [ ] https://github.com/InseeFr/Lunatic/issues/606
- [ ] https://github.com/InseeFr/Lunatic/issues/707
- [ ] https://github.com/InseeFr/Lunatic/issues/607
- [ ] https://github.com/InseeFr/Lunatic/issues/608

__Dynamic tables__
- [ ] https://github.com/InseeFr/Lunatic/issues/609

# Progress
_describe progress_

# Release date
_here we want to keep track of deadlines; and provide links to milestones_

**Comment by AgatheLM** [comment]
Hi,

For december MVP here is the priority :
- https://github.com/InseeFr/Bowie/issues/77
- https://github.com/InseeFr/Bowie/issues/75
- https://github.com/InseeFr/Bowie/issues/76
- https://github.com/InseeFr/Lunatic/issues/606
- https://github.com/InseeFr/Lunatic/issues/608
- https://github.com/InseeFr/Lunatic/issues/604

And after :

- https://github.com/InseeFr/Bowie/issues/78
- https://github.com/InseeFr/Bowie/issues/80
- https://github.com/InseeFr/Lunatic/issues/609

We have other needs, like :
  - merged head cell 
  - label in first column head cell
  
![image](https://github.com/InseeFr/Bowie/assets/35449676/de47f26f-bab0-4bf5-b48c-efd6e7435be9)

**Comment by Wemelbeke** [comment]
Désolé,  je suis nul en anglais, donc je préfère l'écrire en français.

Mise en forme des tableaux statiques et dynamiques :
- Pouvoir fusionner une en-tête de colonne sous cette forme 
![image](https://github.com/InseeFr/Bowie/assets/116063644/e132bcc2-a94f-4e2c-a9e8-90a91d00f4a1)
- pour les tableaux dynamiques : pouvoir supprimer une ligne du tableau autre que la dernière ligne

- Pouvoir insérer la valeur d'une variable calculée dans un tableau sans que celle-ci puisse être directement modifié
    - [ ] insérer une variable caculée
    - [ ] Rendre unedited une variable

- A partir d'un tableau dynamique, reprendre les valeurs renseignées dans une colonne et réutiliser ces données pour "personnaliser" un autre tableau dynamiques dans le quesitonnaire  

Par exemple, l'unité enquêté a rempli le tableau dynmaique ci-dessous avec ces valeurs
Tableau 1
| item1 | item2 |
| ------ | ------ |
| valeurA1 | ValeurC1 |
| valeurA2 | ValeurC2 |
| valeurA3 | ValeurC3 |
| valeurA4 | ValeurC4 |
| Ajouter/supprimer un ligne |  |

Quand il arrive sur tableau2, on veut que les valeurs de la colonne item1 du tableau 1 soient reprise dans tableau2, mais qu'elle ne soient pas modifiable
Il arriverait sur un tableau de ce type :

Tableau 2
| item1 | item_tab2 |
| ------ | ------ |
| valeurA1 |  |
| valeurA2 |  |
| valeurA3 |  |
| valeurA4 |  |

**Comment by AnneHuSKa** [comment]
Résumé demandes Agathe

**Echéance Mars 2024**

- [x] Tableau dynamique avec un suggester en première colonne
  - Liste EAP à fournir 
- [ ] https://github.com/InseeFr/Lunatic/issues/606 : semble compliqué, en cours @ddecrulle 

**Echéance mi-juin 2024**
- [ ]  https://github.com/InseeFr/Bowie/issues/77 : ok Lunatic, Pogues et Eno à faire (si eno seul : https://github.com/InseeFr/Eno/issues/1006)
- [ ]  https://github.com/InseeFr/Bowie/issues/75 : ?
- [ ] https://github.com/InseeFr/Bowie/issues/76 : fonctionnalité "case non collectée" de Pogues/eno/Lunatic ok ?
- [ ] https://github.com/InseeFr/Bowie/issues/52 : pas de suite
- [x] https://github.com/InseeFr/Lunatic/issues/604

And after :

- Tableau liée pour utiliser dans plusieurs tableaux la même variable vecteur 🎫  A spécifier
- [x] Tableaux récapitulatif avec des totaux de somme en colonne présentée dans une ligne finale : fonctionnalité "case non collectée" de Pogues/eno/Lunatic ok ?
- https://github.com/InseeFr/Bowie/issues/80 : pas à court terme, issue fermée
- https://github.com/InseeFr/Lunatic/issues/609:  attendre a minima le support des Dataset dans Trevas JS pour les boucles, issue fermée
- https://github.com/InseeFr/Bowie/issues/78 ; très complexe, changement dynamique de nb de colonnes, Indispensable ?

We have other needs, like :
  - merged head cell  -  label in first column head cell : pas à moyen terme.
  
![image](https://github.com/InseeFr/Bowie/assets/35449676/de47f26f-bab0-4bf5-b48c-efd6e7435be9).

**Comment by AnneHuSKa** [comment]
Reste à faire migrer dans workplace
